version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket trialbucket101target --output-template-file output_template.yaml
artifacts:
  type: yaml
  files:
    - output_template.yaml